name: Test Publications Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create test JSON
        run: |
          echo '{ "status": "OK", "message": "Workflow fonctionne" }' > publications.json

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add publications.json
          git commit -m "add publications.json" || exit 0
          git push
